name: RLHF Canary Nightly

on:
  schedule:
    - cron: '0 2 * * *'  # 2 AM UTC daily
  workflow_dispatch:
    inputs:
      config:
        description: 'Config file to use'
        required: false
        default: 'configs/dpo_nightly.yaml'

jobs:
  canary-nightly:
    name: DPO Nightly Soak Test
    runs-on: ubuntu-latest
    # Use GPU runner for real runs
    # runs-on: [self-hosted, gpu]
    timeout-minutes: 180  # 3 hour timeout for nightly

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -e ".[dev]"
          pip install torch --index-url https://download.pytorch.org/whl/cpu

      - name: Show environment
        run: canary env

      - name: Download baseline (if exists)
        id: download-baseline
        continue-on-error: true
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: nightly_canary.yml
          branch: main
          name: canary-nightly-baseline
          path: baseline/

      - name: Run nightly canary
        id: canary
        run: |
          CONFIG="${{ github.event.inputs.config || 'configs/dpo_nightly.yaml' }}"
          echo "Running nightly canary with config: $CONFIG"
          canary run $CONFIG -o ./canary_output

          # Find the metrics file
          METRICS=$(find ./canary_output -name "metrics.json" | head -1)
          echo "metrics_path=$METRICS" >> $GITHUB_OUTPUT

      - name: Compare to baseline
        id: compare
        if: steps.download-baseline.outcome == 'success'
        continue-on-error: true
        run: |
          BASELINE=$(find ./baseline -name "metrics.json" | head -1)
          CURRENT="${{ steps.canary.outputs.metrics_path }}"

          if [ -n "$BASELINE" ] && [ -n "$CURRENT" ]; then
            echo "Comparing $CURRENT to $BASELINE"
            canary compare "$CURRENT" "$BASELINE" --threshold-tier nightly -o comparison.md
            cat comparison.md >> $GITHUB_STEP_SUMMARY
          else
            echo "No baseline found, skipping comparison"
          fi

      - name: Upload comparison artifact
        if: steps.compare.outcome != 'skipped'
        uses: actions/upload-artifact@v4
        with:
          name: canary-nightly-comparison
          path: comparison.md
          retention-days: 30
          if-no-files-found: ignore

      - name: Upload metrics as artifact
        uses: actions/upload-artifact@v4
        with:
          name: canary-nightly-metrics
          path: ./canary_output/**/metrics.json
          retention-days: 30

      - name: Update baseline on main
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: canary-nightly-baseline
          path: ./canary_output/**/metrics.json
          retention-days: 90

      - name: Check comparison result
        if: steps.compare.outcome == 'failure'
        run: |
          echo "::error::Nightly canary regression detected! See comparison report above."
          exit 1

      - name: Summary on success
        if: success()
        run: |
          echo "## Nightly Canary Completed Successfully" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- Config: ${{ github.event.inputs.config || 'configs/dpo_nightly.yaml' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Metrics: \`${{ steps.canary.outputs.metrics_path }}\`" >> $GITHUB_STEP_SUMMARY
